"use client";
import Link from "next/link";
import { LogoFull } from "@/components/Logo";
import { SiteFooter } from "@/components/SiteFooter";
import { LanguageSwitcher } from "@/components/LanguageSwitcher";
import { LegalBody, type LegalSection } from "@/components/LegalBody";
import { useLang } from "@/lib/language-context";

/**
 * Every factual claim below is checked against the code, not against what the
 * product would like to be true. The ones that took a reading to get right, and
 * that will silently rot if the code changes without this file:
 *
 *   - BYOK is open to every PAID plan (BYOK_PLANS in /api/admin/company:
 *     personal, professional, enterprise, custom) — NOT "Professional and up",
 *     which is what a stale comment in db/schema.ts still says. Free Starter
 *     cannot connect keys, so a free account has no way out of our shared
 *     provider accounts. That asymmetry is the single most consequential fact on
 *     this page, which is why section 5 is highlighted and says it in bold.
 *   - BYOK is per provider, and the two providers are treated differently on
 *     purpose (see isConfigured in @/lib/models). Groq falls back to our
 *     platform account; Google never does, because our Google account is the
 *     free tier this feature exists to escape. Section 5 states both.
 *   - There is no auto-renewal anywhere in the payment code — Midtrans Snap
 *     issues one-off transactions and nothing stores a recurring token. The old
 *     wording ("cancel any time, effective at the end of the billing period")
 *     described a subscription this app has never had, and implying an
 *     auto-debit that does not exist is the kind of clause a consumer dispute
 *     turns on. Section 8.
 *   - Free Starter is search-only (canUseAiAnswers in @/lib/pricing), so
 *     "layanan chat AI" is not something every plan gets. Sections 2 and 11.
 *   - The numbers in section 11 are PLAN_LIMITS verbatim, with one deliberate
 *     omission: Starter's question allowance is not quoted, for the same reason
 *     the pricing copy stopped quoting it (see @/lib/i18n) — the tier has no AI
 *     answers, so printing a per-day figure promises a chat the app declines to
 *     give. If PLAN_LIMITS moves, this moves with it.
 */

const ID_SECTIONS: readonly LegalSection[] = [
  { title: "1. Penerimaan Syarat", body: "Dengan mendaftar dan menggunakan layanan IntelliBase AI, Anda menyetujui untuk terikat oleh Syarat dan Ketentuan ini beserta Kebijakan Privasi kami, yang keduanya merupakan satu kesatuan perjanjian. Jika Anda mendaftar atas nama sebuah organisasi, Anda menyatakan berwenang mengikat organisasi tersebut pada syarat ini. Layanan ini ditujukan untuk pengguna yang cakap secara hukum. Jika Anda tidak menyetujui syarat ini, harap tidak menggunakan layanan kami." },
  { title: "2. Deskripsi Layanan", body: "IntelliBase AI adalah platform SaaS (Software as a Service) berupa knowledge base internal berbasis AI. Tersedia dua jenis akun: akun Perusahaan (admin, karyawan, departemen) dan akun Individu (satu orang, satu ruang kerja). Layanan mencakup: unggah dokumen berformat PDF, DOCX, XLSX, dan PPTX dengan ukuran maksimum 4 MB per file; ekstraksi teks dari dokumen tersebut; pembuatan indeks pencarian vektor; pencarian dokumen; dan antarmuka chat AI yang menjawab dengan mengutip dokumen Anda. Impor dokumen dari Google Drive dan integrasi Slack tersedia pada paket berbayar. **Paket Free Starter hanya memperoleh pencarian dokumen — jawaban AI hanya tersedia pada paket berbayar.**" },
  { title: "3. Akun dan Keamanan", body: "Anda bertanggung jawab atas kerahasiaan kredensial akun Anda, dan setiap aktivitas yang terjadi di bawah akun Anda adalah tanggung jawab Anda. Verifikasi dua langkah (2FA) tersedia dan kami sarankan diaktifkan, terutama untuk akun admin. Pada akun Perusahaan, admin dapat membuat, menonaktifkan, dan mereset kata sandi akun karyawan di ruang kerjanya; karyawan yang bersangkutan diberi tahu melalui email saat kata sandinya direset oleh admin. Segera hubungi kami jika Anda mencurigai adanya akses tidak sah." },
  { title: "4. Peran Para Pihak atas Data Pribadi", body: "Sesuai UU No. 27 Tahun 2022 tentang Pelindungan Data Pribadi: atas isi dokumen yang Anda unggah dan data karyawan yang Anda daftarkan, **Anda adalah Pengendali Data Pribadi dan IntelliBase AI adalah Prosesor Data Pribadi** yang memproses data tersebut atas instruksi Anda melalui fitur-fitur layanan. Anda bertanggung jawab memastikan tersedianya dasar pemrosesan yang sah atas data pribadi yang Anda masukkan ke dalam layanan, termasuk memberitahu karyawan Anda. Untuk data akun, data penagihan, dan data teknis operasional, kami bertindak sebagai Pengendali. Rincian pemrosesan ada di Kebijakan Privasi." },
  { title: "5. Kepemilikan Data dan Pemrosesan oleh Penyedia AI", highlight: true, body: "Dokumen dan data yang Anda unggah tetap menjadi milik Anda sepenuhnya. IntelliBase AI tidak melatih model AI dengan data Anda, tidak menjualnya, dan tidak menggunakannya di luar layanan yang disepakati. Namun layanan ini berjalan di atas penyedia AI pihak ketiga, dan **Anda perlu memahami hal berikut sebelum mengunggah dokumen apa pun**. Seluruh isi dokumen yang Anda unggah dikirim ke Google (Gemini API) untuk dibuatkan indeks pencarian. Saat sebuah pertanyaan dijawab, potongan dokumen yang relevan dikirim ke Groq Inc.; apabila Groq sedang mencapai batas pemakaian, potongan tersebut dikirim ke Google (Gemini API) agar pertanyaan tetap terjawab. Bagian awal dokumen (sekitar 2.000 karakter pertama) juga dikirim ke Groq untuk membuat ringkasan otomatis. Groq menyatakan tidak memakai data API pelanggan untuk melatih modelnya. **Akun Gemini kami saat ini berada pada tier gratis, dan ketentuan Google untuk tier tersebut mengizinkan Google memakai konten yang dikirim untuk meningkatkan layanannya, termasuk pelatihan model.** Jika Anda tidak menghendaki hal tersebut, tersedia jalan keluar yang dapat Anda aktifkan sendiri: **pada seluruh paket berbayar — Personal untuk akun Individu, serta Professional, Enterprise, dan Custom untuk akun Perusahaan — Anda dapat memasang API key Groq dan Gemini milik Anda sendiri melalui menu Langganan di dasbor admin, sehingga indexing dan jawaban diproses melalui akun penyedia Anda, bukan akun kami. Fitur ini tidak tersedia pada paket Free Starter, sehingga dokumen pada akun gratis selalu diproses melalui akun penyedia bersama milik kami, termasuk akun Gemini tier gratis di atas.** Kunci tersebut disimpan dalam keadaan terenkripsi dan dapat Anda hapus kapan saja. Perlu dicatat bahwa kunci berlaku per penyedia: bila Anda hanya memasang kunci Gemini, pertanyaan tetap dijawab melalui akun Groq kami; dan bila Anda memasang kunci tanpa kunci Gemini, kami sengaja menonaktifkan jalur cadangan Gemini alih-alih mengalihkan dokumen Anda ke akun Gemini gratis kami. Pemrosesan di sisi penyedia tunduk pada ketentuan masing-masing penyedia dan berada di luar kendali kami. Dengan mengunggah dokumen, Anda menyatakan telah memahami ketentuan ini dan berwenang mengunggah dokumen tersebut." },
  { title: "6. Data Pribadi Bersifat Spesifik dan Rekam Medis", highlight: true, body: "Layanan ini dirancang untuk dokumen referensi internal — SPO, clinical pathway, PPK, kebijakan, panduan akreditasi, instruksi kerja, dan sejenisnya. **Layanan ini tidak dirancang, tidak diuji, dan tidak boleh digunakan untuk mengunggah rekam medis pasien, data kesehatan perorangan, data keuangan pribadi, data biometrik, atau data pribadi bersifat spesifik lainnya sebagaimana dimaksud dalam UU PDP.** Mohon hilangkan identitas pasien dan data pribadi perorangan dari dokumen sebelum diunggah. Apabila kebutuhan Anda tetap mengharuskan pemrosesan data pribadi bersifat spesifik, hubungi kami terlebih dahulu di hello@intellibaseai.com untuk perjanjian pemrosesan data tertulis; pemrosesan semacam itu sekurang-kurangnya mensyaratkan paket berbayar dengan API key milik Anda sendiri sebagaimana diuraikan pada bagian 5." },
  { title: "7. Isolasi Data Antar-Penyewa", body: "Data setiap ruang kerja disimpan dan diproses secara terisolasi. Isolasi ditegakkan pada dua lapis: Row-Level Security di tingkat basis data, dan pemeriksaan otorisasi di setiap jalur permintaan aplikasi. Pada akun Perusahaan, dokumen dapat ditandai milik departemen tertentu; karyawan hanya dapat menerima jawaban dari dokumen departemennya sendiri dan dokumen yang ditandai sebagai dokumen bersama." },
  { title: "8. Pembayaran dan Langganan", highlight: true, body: "Paket berbayar dijual per periode 1 (satu) bulan dan dibayar di muka melalui Midtrans, gateway pembayaran berlisensi Bank Indonesia. Kami tidak menerima, menyimpan, atau memproses nomor kartu Anda; seluruh data pembayaran ditangani oleh Midtrans. **Langganan tidak diperpanjang secara otomatis dan kami tidak pernah melakukan penarikan dana otomatis (auto-debit). Setiap periode berikutnya harus Anda beli kembali secara manual, sehingga tidak ada yang perlu Anda batalkan untuk berhenti — cukup tidak melakukan pembelian berikutnya.** Harga promo peluncuran berlaku sampai dengan 31 Desember 2026 dan setelahnya harga kembali ke harga normal yang tercantum di halaman harga. Paket Personal hanya dapat dibeli oleh akun Individu, sedangkan paket Professional dan Enterprise hanya dapat dibeli oleh akun Perusahaan. Paket Custom tidak dijual secara mandiri dan hanya diberikan berdasarkan kesepakatan tertulis." },
  { title: "9. Masa Berlaku, Masa Tenggang, dan Penurunan Paket", body: "Saat masa berlaku paket berakhir, layanan berbayar tetap berjalan penuh selama **masa tenggang 7 (tujuh) hari**. Setelah masa tenggang berakhir tanpa pembelian baru, akun otomatis turun ke paket Free Starter beserta seluruh batasannya, termasuk hilangnya jawaban AI. **Dokumen dan akun karyawan yang melebihi batas paket gratis dibekukan, bukan dihapus**, dan aktif kembali segera setelah Anda berlangganan lagi. Penghapusan data hanya terjadi atas permintaan Anda atau sesuai bagian retensi pada Kebijakan Privasi." },
  { title: "10. Kebijakan Pengembalian Dana", body: "Karena sifat layanan digital, pembayaran yang telah berhasil diproses tidak dapat dikembalikan (non-refundable). Pengecualian: apabila terjadi gangguan teknis dari pihak kami yang menyebabkan layanan tidak dapat digunakan lebih dari 72 jam berturut-turut, kami memberikan kompensasi perpanjangan masa langganan setara durasi gangguan. Untuk klaim, hubungi hello@intellibaseai.com dalam 7 hari sejak gangguan terjadi." },
  { title: "11. Batasan Penggunaan dan Sifat Jawaban AI", body: "Setiap paket memiliki batas dokumen, batas jumlah akun, dan batas pertanyaan yang tercantum di halaman harga dan berlaku sebagaimana adanya di dalam aplikasi: Free Starter 10 dokumen dan 5 akun, dengan pencarian dokumen saja tanpa jawaban AI; Personal 50 dokumen, 1 akun, 60 pertanyaan per hari; Professional 100 dokumen, 50 akun, 300 pertanyaan per hari dengan batas kewajaran 60 pertanyaan per pengguna per hari; Enterprise 500 dokumen, 200 akun, 2.000 pertanyaan per hari dengan batas kewajaran 400 pertanyaan per pengguna per hari. Ukuran maksimum tiap file adalah 4 MB. Jawaban dihasilkan secara otomatis dari dokumen yang Anda unggah dan **dapat keliru atau tidak lengkap; kami tidak menjamin keakuratannya dan Anda wajib memverifikasi informasi penting pada sumber resmi Anda sendiri.**" },
  { title: "12. Penggunaan yang Dilarang", body: "Anda dilarang: menggunakan layanan untuk tujuan yang melanggar hukum; mengunggah dokumen yang tidak Anda miliki atau tanpa wewenang untuk memprosesnya; mengunggah konten berbahaya, melanggar hak kekayaan intelektual pihak ketiga, atau data pribadi bersifat spesifik sebagaimana bagian 6; membagikan kredensial akun kepada pihak di luar organisasi Anda; melakukan rekayasa balik, pengujian penetrasi tanpa izin tertulis, atau upaya membebani dan merusak sistem; serta menggunakan layanan untuk membangun produk pesaing." },
  { title: "13. Penghentian Layanan", body: "Kami berhak menangguhkan atau menghentikan akses akun yang melanggar syarat penggunaan. Untuk pelanggaran yang tidak membahayakan sistem atau pihak lain, kami akan lebih dulu memberi peringatan dan kesempatan memperbaiki. Anda dapat berhenti kapan saja dengan tidak memperpanjang langganan dan dapat meminta penghapusan data sesuai Kebijakan Privasi." },
  { title: "14. Hukum yang Berlaku", body: "Syarat dan Ketentuan ini diatur oleh hukum Republik Indonesia. Setiap sengketa diselesaikan terlebih dahulu melalui musyawarah mufakat dalam waktu 30 hari; apabila tidak tercapai, sengketa diselesaikan melalui jalur hukum di Indonesia." },
  { title: "15. Perubahan Syarat", body: "Kami dapat memperbarui syarat ini sewaktu-waktu. Perubahan material akan diberitahukan melalui email atau notifikasi dalam aplikasi minimal 14 hari sebelum berlaku. Perubahan pada daftar penyedia AI atau pada cara data Anda diproses termasuk perubahan material." },
  { title: "16. Disclaimer Layanan 'Sebagaimana Adanya'", body: "Layanan IntelliBase AI disediakan 'sebagaimana adanya' (as-is) dan 'sebagaimana tersedia' (as-available) tanpa jaminan dalam bentuk apapun, baik tersurat maupun tersirat, termasuk namun tidak terbatas pada jaminan kelayakan untuk tujuan tertentu, ketersediaan tanpa gangguan, atau bebas dari kesalahan. Kami tidak menjamin bahwa layanan akan selalu tersedia, aman, atau bebas dari bug." },
  { title: "17. Batasan Tanggung Jawab", body: "Sejauh diizinkan oleh hukum yang berlaku, total kewajiban IntelliBase AI kepada Anda atas segala klaim yang timbul dari atau terkait dengan penggunaan layanan ini tidak akan melebihi jumlah total yang telah Anda bayarkan kepada kami dalam periode 3 (tiga) bulan kalender sebelum tanggal klaim diajukan. Batasan ini berlaku terlepas dari bentuk tuntutan, apakah berdasarkan kontrak, perbuatan melawan hukum, atau dasar hukum lainnya, dan tidak berlaku untuk hal-hal yang menurut hukum tidak dapat dibatasi." },
  { title: "18. Pengecualian Kerugian Tidak Langsung", body: "Kami tidak bertanggung jawab atas kerugian tidak langsung, insidental, khusus, konsekuensial, atau kerugian yang bersifat hukuman, termasuk namun tidak terbatas pada: kehilangan keuntungan bisnis, kehilangan data, gangguan operasional bisnis, atau kerusakan reputasi, yang timbul dari penggunaan atau ketidakmampuan menggunakan layanan ini, meskipun kami telah diberitahu tentang kemungkinan kerugian tersebut. Pengguna bertanggung jawab penuh atas keputusan bisnis yang diambil berdasarkan output layanan." },
  { title: "19. Disclaimer Khusus AI", body: "Output yang dihasilkan oleh sistem AI IntelliBase bersifat otomatis berdasarkan dokumen yang Anda unggah dan **bukan merupakan nasihat profesional di bidang medis, hukum, keuangan, atau bidang lain yang memerlukan lisensi profesional.** Output tidak boleh dijadikan dasar tunggal untuk keputusan klinis atau keputusan berisiko lainnya. Kami tidak bertanggung jawab atas konsekuensi apapun yang timbul dari penggunaan atau ketergantungan pada output AI. Pengguna wajib melakukan verifikasi mandiri dan berkonsultasi dengan profesional yang berwenang sebelum mengambil keputusan penting." },
  { title: "20. Force Majeure", body: "Kami tidak bertanggung jawab atas keterlambatan atau kegagalan pelaksanaan kewajiban yang disebabkan oleh keadaan di luar kendali wajar kami, termasuk namun tidak terbatas pada: bencana alam, pemadaman listrik, gangguan infrastruktur internet, gangguan atau penghentian layanan oleh penyedia pihak ketiga yang kami gunakan, serangan siber, regulasi pemerintah, pandemi, atau kejadian lain yang secara umum diklasifikasikan sebagai force majeure." },
  { title: "21. Ganti Rugi dari Pengguna (Indemnifikasi)", body: "Anda setuju untuk menanggung, membela, dan membebaskan IntelliBase AI beserta pengelolanya dari dan terhadap segala klaim, kerugian, kewajiban, biaya, dan pengeluaran (termasuk biaya hukum yang wajar) yang timbul dari: (a) pelanggaran Anda terhadap Syarat dan Ketentuan ini; (b) penggunaan layanan oleh Anda yang melanggar hukum atau hak pihak ketiga; (c) konten atau dokumen yang Anda unggah ke platform, termasuk ketiadaan dasar pemrosesan yang sah atas data pribadi di dalamnya." },
  { title: "22. Kontak", body: "Untuk pertanyaan terkait syarat ini, hubungi kami di: hello@intellibaseai.com" },
];

const EN_SECTIONS: readonly LegalSection[] = [
  { title: "1. Acceptance of Terms", body: "By registering and using IntelliBase AI, you agree to be bound by these Terms and Conditions together with our Privacy Policy, which together form a single agreement. If you register on behalf of an organisation, you represent that you are authorised to bind that organisation to these terms. The service is intended for users with legal capacity to contract. If you do not agree, please do not use our service." },
  { title: "2. Service Description", body: "IntelliBase AI is a SaaS platform providing an AI-powered internal knowledge base. Two account types exist: Company accounts (admin, employees, departments) and Individual accounts (one person, one workspace). The service includes: uploading documents in PDF, DOCX, XLSX and PPTX format up to 4 MB per file; text extraction from those documents; building a vector search index; document search; and an AI chat interface that answers by citing your documents. Google Drive import and the Slack integration are available on paid plans. **The Free Starter plan gets document search only — AI answers are available on paid plans.**" },
  { title: "3. Account and Security", body: "You are responsible for the confidentiality of your account credentials, and all activity under your account is your responsibility. Two-factor authentication (2FA) is available and we recommend enabling it, particularly for admin accounts. On Company accounts, an admin can create, deactivate and reset the passwords of employee accounts in their workspace; the employee concerned is notified by email when an admin resets their password. Contact us immediately if you suspect unauthorised access." },
  { title: "4. Roles of the Parties Regarding Personal Data", body: "Under Indonesian Law No. 27 of 2022 on Personal Data Protection: with respect to the contents of documents you upload and the employee data you register, **you are the Data Controller and IntelliBase AI is the Data Processor**, processing that data on your instructions through the features of the service. You are responsible for ensuring a lawful basis exists for any personal data you put into the service, including informing your employees. For account data, billing data and operational technical data, we act as Controller. Processing details are set out in the Privacy Policy." },
  { title: "5. Data Ownership and Processing by AI Providers", highlight: true, body: "Documents and data you upload remain entirely yours. IntelliBase AI does not train AI models on your data, does not sell it, and does not use it beyond the agreed services. However, this service runs on top of third-party AI providers, and **you should understand the following before uploading anything**. The full contents of documents you upload are sent to Google (Gemini API) to build a search index. When a question is answered, the relevant document excerpts are sent to Groq Inc.; if Groq is at its usage limit, those excerpts are sent to Google (Gemini API) instead so the question can still be answered. The opening of each document (roughly the first 2,000 characters) is also sent to Groq to generate an automatic summary. Groq states that it does not use customer API data to train its models. **Our Gemini account is currently on the free tier, and Google's terms for that tier allow Google to use submitted content to improve their services, including model training.** If that is not acceptable to you, there is a way out you can switch on yourself: **on every paid plan — Personal for Individual accounts, and Professional, Enterprise and Custom for Company accounts — you can install your own Groq and Gemini API keys from the Subscription tab in the admin dashboard, so that indexing and answers are processed through your provider accounts rather than ours. This feature is not available on the Free Starter plan, so documents on a free account are always processed through our shared provider accounts, including the free-tier Gemini account described above.** Those keys are stored encrypted and you can remove them at any time. Note that keys apply per provider: if you install only a Gemini key, questions are still answered through our Groq account; and if you install keys without a Gemini key, we deliberately disable the Gemini fallback rung rather than routing your documents into our free-tier Gemini account. Processing on the providers' side is governed by their respective terms and is outside our control. By uploading documents you confirm that you understand these terms and are authorised to upload them." },
  { title: "6. Specific Personal Data and Medical Records", highlight: true, body: "This service is designed for internal reference documents — SOPs, clinical pathways, clinical practice guidelines, policies, accreditation manuals, work instructions and the like. **It is not designed for, not tested for, and must not be used to upload patient medical records, individual health data, personal financial data, biometric data, or other specific personal data as defined by the Indonesian PDP Law.** Please remove patient identifiers and individual personal data from documents before uploading. If your use case nonetheless requires processing specific personal data, contact us first at hello@intellibaseai.com for a written data processing agreement; such processing requires, at minimum, a paid plan using your own API keys as described in section 5." },
  { title: "7. Multi-Tenant Data Isolation", body: "Each workspace's data is stored and processed in isolation. Isolation is enforced in two layers: Row-Level Security at the database level, and authorisation checks on every application request path. On Company accounts, documents can be tagged as belonging to a specific department; an employee only ever receives answers from their own department's documents and documents marked as shared." },
  { title: "8. Payment and Subscription", highlight: true, body: "Paid plans are sold in 1 (one) month periods, paid in advance via Midtrans, a payment gateway licensed by Bank Indonesia. We do not receive, store or process your card numbers; all payment data is handled by Midtrans. **Subscriptions do not renew automatically and we never take an automatic payment (auto-debit). Each subsequent period must be purchased again manually, so there is nothing to cancel in order to stop — simply do not make the next purchase.** Launch promo pricing applies through 31 December 2026, after which prices revert to the normal prices shown on the pricing page. The Personal plan can only be purchased by Individual accounts, while Professional and Enterprise can only be purchased by Company accounts. The Custom plan is not sold self-serve and is granted only under a written agreement." },
  { title: "9. Term, Grace Period and Downgrade", body: "When a plan's term ends, paid service continues in full for a **7 (seven) day grace period**. After the grace period ends without a new purchase, the account is automatically downgraded to Free Starter with all of its limits, including the loss of AI answers. **Documents and employee accounts above the free plan's limits are frozen, not deleted**, and become active again as soon as you subscribe again. Data is deleted only at your request or as described in the retention section of the Privacy Policy." },
  { title: "10. Refund Policy", body: "Due to the digital nature of the service, successfully processed payments are non-refundable. Exception: if a technical failure on our part renders the service unusable for more than 72 consecutive hours, we will provide a subscription extension equal to the outage duration. To file a claim, contact hello@intellibaseai.com within 7 days of the incident." },
  { title: "11. Usage Limits and the Nature of AI Answers", body: "Each plan has document, account and question limits that are listed on the pricing page and enforced as stated in the application: Free Starter 10 documents and 5 accounts, with document search only and no AI answers; Personal 50 documents, 1 account, 60 questions per day; Professional 100 documents, 50 accounts, 300 questions per day with a fair-use cap of 60 questions per user per day; Enterprise 500 documents, 200 accounts, 2,000 questions per day with a fair-use cap of 400 questions per user per day. Maximum file size is 4 MB. Answers are generated automatically from the documents you upload and **may be wrong or incomplete; we do not guarantee their accuracy and you must verify important information against your own official sources.**" },
  { title: "12. Prohibited Use", body: "You must not: use the service for unlawful purposes; upload documents you do not own or are not authorised to process; upload harmful content, content infringing third-party intellectual property, or specific personal data as described in section 6; share account credentials outside your organisation; reverse engineer the service, run penetration tests without written permission, or attempt to overload or damage the system; or use the service to build a competing product." },
  { title: "13. Service Termination", body: "We reserve the right to suspend or terminate access to accounts that violate these terms. For violations that do not endanger the system or other parties, we will first give notice and an opportunity to remedy. You may stop at any time by not renewing, and may request deletion of your data as described in the Privacy Policy." },
  { title: "14. Governing Law", body: "These Terms are governed by the laws of the Republic of Indonesia. Any dispute shall first be pursued through good-faith negotiation for 30 days; failing that, it shall be resolved through legal channels in Indonesia." },
  { title: "15. Changes to Terms", body: "We may update these terms at any time. Material changes will be communicated via email or in-app notification at least 14 days before taking effect. Changes to the list of AI providers or to how your data is processed count as material changes." },
  { title: "16. 'As-Is' Service Disclaimer", body: "The IntelliBase AI service is provided 'as-is' and 'as-available' without warranties of any kind, whether express or implied, including but not limited to implied warranties of fitness for a particular purpose, uninterrupted availability, or freedom from errors. We do not guarantee that the service will always be available, secure, or free of bugs." },
  { title: "17. Limitation of Liability", body: "To the fullest extent permitted by applicable law, IntelliBase AI's total liability to you for any claims arising from or related to your use of this service shall not exceed the total amount you have paid to us in the 3 (three) calendar months preceding the date the claim is submitted. This limitation applies regardless of the form of action, whether based in contract, tort, or any other legal theory, and does not apply to liabilities that cannot be limited by law." },
  { title: "18. Exclusion of Indirect Damages", body: "We are not liable for indirect, incidental, special, consequential, or punitive damages, including but not limited to: loss of business profits, data loss, business interruption, or reputational harm, arising from your use of or inability to use this service, even if we have been advised of the possibility of such damages. Users are solely responsible for business decisions made based on the service's output." },
  { title: "19. AI-Specific Disclaimer", body: "Output generated by the IntelliBase AI system is automated, based on documents you upload, and **does not constitute professional advice in medical, legal, financial, or any other field requiring professional licensing.** It must not be the sole basis for clinical or other high-risk decisions. We are not responsible for any consequences arising from the use of or reliance on AI output. Users must independently verify information and consult qualified professionals before making important decisions." },
  { title: "20. Force Majeure", body: "We are not liable for delays or failures in performing our obligations caused by circumstances beyond our reasonable control, including but not limited to: natural disasters, power outages, internet infrastructure failures, disruption or discontinuation of service by the third-party providers we rely on, cyber attacks, government regulation, pandemics, or other events generally classified as force majeure." },
  { title: "21. User Indemnification", body: "You agree to indemnify, defend, and hold harmless IntelliBase AI and its operators from and against any claims, losses, liabilities, costs, and expenses (including reasonable legal fees) arising from: (a) your breach of these Terms and Conditions; (b) your use of the service in violation of law or third-party rights; (c) content or documents you upload to the platform, including the absence of a lawful basis for processing any personal data within them." },
  { title: "22. Contact", body: "For questions about these terms, contact us at: hello@intellibaseai.com" },
];

const CONTENT = {
  id: {
    title: "Syarat & Ketentuan",
    updated: "Terakhir diperbarui: 19 Agustus 2026",
    login: "Masuk",
    intro: "Bagian yang disorot memuat hal-hal yang perlu Anda putuskan sebelum mengunggah dokumen: ke mana data Anda dikirim, cara memprosesnya melalui akun penyedia Anda sendiri, dokumen apa yang tidak boleh diunggah, dan bagaimana penagihan bekerja.",
    sections: ID_SECTIONS,
  },
  en: {
    title: "Terms & Conditions",
    updated: "Last updated: August 19, 2026",
    login: "Sign In",
    intro: "The highlighted sections cover what you need to decide before uploading documents: where your data is sent, how to process it through your own provider accounts, which documents must not be uploaded, and how billing works.",
    sections: EN_SECTIONS,
  },
};

export default function TermsPage() {
  const { lang } = useLang();
  const T = CONTENT[lang];

  return (
    <div className="min-h-screen bg-background">
      <nav className="border-b px-6 py-3 flex items-center justify-between">
        <Link href="/"><LogoFull size="sm" /></Link>
        <div className="flex items-center gap-3">
          <LanguageSwitcher />
          <Link href="/login" className="text-sm text-blue-600 hover:underline">{T.login}</Link>
        </div>
      </nav>
      <main className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-2xl md:text-3xl font-semibold tracking-[-0.015em] text-gray-900 mb-2">{T.title}</h1>
        <p className="text-gray-400 text-sm mb-6">{T.updated}</p>
        <p className="text-sm leading-relaxed text-gray-600 mb-10">{T.intro}</p>
        <LegalBody sections={T.sections} />
      </main>
      <SiteFooter lang={lang} />
    </div>
  );
}
