"use client";
import Link from "next/link";
import { LogoFull } from "@/components/Logo";
import { SiteFooter } from "@/components/SiteFooter";
import { LanguageSwitcher } from "@/components/LanguageSwitcher";
import { LegalBody, type LegalSection } from "@/components/LegalBody";
import { useLang } from "@/lib/language-context";

/**
 * Written against the code, and the four facts that were missing or wrong
 * before — each of them the kind a regulator or a customer's DPO asks about
 * first:
 *
 *   - Google Analytics 4 was not disclosed at all (see AnalyticsConsent), nor
 *     was Vercel Web Analytics, nor Resend, nor Vercel as the host. A named
 *     third-party list that is missing four names is worse than none, because
 *     it reads as exhaustive.
 *   - Cookies: the language preference is localStorage, not a cookie. Section 10
 *     now describes what the app actually writes.
 *   - Storage location: the database is Neon on AWS ap-southeast-1 (Singapore).
 *     A cross-border transfer is a disclosure obligation under UU PDP, and
 *     "server berbasis cloud" does not make it.
 *   - A company admin can read every employee's questions and answers, by name
 *     and email (/api/admin/audit). Employees are data subjects who never see
 *     these terms at signup, so this is the one clause written for them —
 *     highlighted, section 6.
 *
 * The AI-provider section is kept deliberately parallel with section 5 of the
 * Terms: same facts, same bolding. If one changes, change both.
 */

const ID_SECTIONS: readonly LegalSection[] = [
  { title: "1. Siapa Kami dan Peran Kami", body: "IntelliBase AI adalah layanan knowledge base internal berbasis AI yang dioperasikan dari Indonesia. Kebijakan ini menjelaskan bagaimana kami memperlakukan data pribadi. Sesuai UU No. 27 Tahun 2022 tentang Pelindungan Data Pribadi: untuk isi dokumen yang Anda unggah dan data karyawan yang Anda daftarkan, **organisasi Anda adalah Pengendali Data Pribadi dan kami adalah Prosesor** yang memproses atas instruksi Anda; untuk data akun, penagihan, dan data teknis operasional, kami bertindak sebagai Pengendali. Kontak untuk seluruh urusan data pribadi: hello@intellibaseai.com" },
  { title: "2. Data yang Kami Kumpulkan", body: "(a) Data akun: nama, alamat email, nama ruang kerja atau perusahaan, jenis akun, peran (admin atau karyawan), departemen, status verifikasi email, status 2FA, serta kata sandi yang disimpan dalam bentuk hash — bukan teks asli. (b) Dokumen: file yang Anda unggah kami ekstraksi menjadi teks; yang kami simpan adalah teks hasil ekstraksi, potongan-potongannya, representasi vektornya, dan ringkasan otomatis. **File aslinya sendiri tidak kami simpan setelah proses ekstraksi selesai.** (c) Aktivitas chat: pertanyaan, jawaban AI beserta kutipan sumbernya, dan penilaian suka/tidak suka. (d) Data teknis: alamat IP dan user agent yang tersimpan pada catatan sesi login, serta alamat IP yang dipakai sementara untuk pembatasan laju permintaan (anti-penyalahgunaan). (e) Data transaksi: order id, paket, jumlah, dan status pembayaran. Kami tidak pernah menerima atau menyimpan nomor kartu Anda. (f) Bila Anda memasang integrasi Slack: id anggota Slack dan alamat email profil Slack, dipakai untuk mencocokkan penanya dengan akun di ruang kerja Anda. (g) Bila Anda mengisi formulir di halaman depan: alamat email, pilihan bahasa, dan apakah Anda mendaftar sebagai perusahaan atau individu." },
  { title: "3. Tujuan dan Dasar Pemrosesan", body: "Data Anda diproses untuk: menyediakan layanan pencarian dan chat AI; mengindeks dokumen; menegakkan batas paket dan kuota; menjaga keamanan dan mencegah penyalahgunaan; memproses pembayaran; mengirim email transaksional (verifikasi, reset kata sandi, pemberitahuan); memberi dukungan; serta memahami penggunaan situs secara agregat. Dasar pemrosesannya adalah pelaksanaan perjanjian dengan Anda, pemenuhan kewajiban hukum (mis. catatan keuangan), kepentingan sah kami yang terbatas pada keamanan dan kelangsungan layanan, dan persetujuan Anda untuk hal-hal yang memang meminta persetujuan seperti analitik dan tindak lanjut pemasaran. **Kami tidak menjual data Anda dan tidak memakai isi dokumen Anda untuk melatih model kami sendiri.**" },
  { title: "4. Pemrosesan oleh Penyedia AI", highlight: true, body: "Layanan ini berjalan di atas penyedia AI pihak ketiga, sehingga isi dokumen Anda meninggalkan sistem kami dalam keadaan berikut. **Seluruh isi dokumen yang Anda unggah dikirim ke Google (Gemini API) untuk dibuatkan indeks pencarian.** Saat sebuah pertanyaan dijawab, pertanyaan tersebut dan potongan dokumen yang relevan dikirim ke Groq Inc.; bila Groq sedang mencapai batas pemakaian, potongan tersebut dikirim ke Google (Gemini API). Bagian awal dokumen (sekitar 2.000 karakter pertama) juga dikirim ke Groq untuk ringkasan otomatis. Groq menyatakan tidak memakai data API pelanggan untuk melatih modelnya. **Akun Gemini kami saat ini berada pada tier gratis, dan ketentuan Google untuk tier tersebut mengizinkan Google memakai konten yang dikirim untuk meningkatkan layanannya, termasuk pelatihan model.** Kami menuliskannya secara terbuka karena inilah satu-satunya hal di halaman ini yang sebaiknya Anda putuskan sebelum, bukan sesudah, mengunggah dokumen. **Jalan keluarnya tersedia pada seluruh paket berbayar — Personal untuk akun Individu, serta Professional, Enterprise, dan Custom untuk akun Perusahaan: pasang API key Groq dan Gemini milik Anda sendiri melalui menu Langganan di dasbor admin, dan sejak saat itu indexing serta jawaban diproses melalui akun penyedia Anda, tunduk pada ketentuan yang Anda sepakati sendiri dengan penyedia tersebut. Paket Free Starter tidak dapat memasang kunci sendiri, sehingga dokumen pada akun gratis selalu diproses melalui akun penyedia bersama milik kami, termasuk akun Gemini tier gratis di atas.** Kunci Anda disimpan terenkripsi dan dapat dihapus kapan saja. Kunci berlaku per penyedia: memasang kunci Gemini saja tidak memindahkan pemrosesan jawaban dari akun Groq kami, dan bila Anda memasang kunci tanpa kunci Gemini, jalur cadangan Gemini kami nonaktifkan alih-alih mengalihkan dokumen Anda ke akun gratis kami." },
  { title: "5. Data Pribadi Bersifat Spesifik", highlight: true, body: "**Layanan ini tidak ditujukan untuk rekam medis pasien, data kesehatan perorangan, data keuangan pribadi, data biometrik, atau data pribadi bersifat spesifik lainnya menurut UU PDP.** Mohon hilangkan identitas perorangan dari dokumen sebelum diunggah — knowledge base ini dirancang untuk dokumen referensi internal seperti SPO, clinical pathway, PPK, kebijakan, dan panduan akreditasi. Sebagaimana bagian 4, isi dokumen dikirim ke penyedia AI pihak ketiga, sehingga mengunggah data pribadi bersifat spesifik ke akun gratis berarti data tersebut diproses pada akun penyedia bersama kami. Bila Anda memang harus memproses data semacam itu, hubungi kami lebih dulu untuk perjanjian pemrosesan data tertulis." },
  { title: "6. Siapa yang Dapat Melihat Data Anda di Dalam Aplikasi", highlight: true, body: "Pada akun Perusahaan, **admin ruang kerja dapat melihat riwayat pertanyaan dan jawaban seluruh karyawan di ruang kerjanya, lengkap dengan nama dan email penanya**, melalui tab Audit Log di dasbor admin. Karyawan perlu mengetahui hal ini: pertanyaan yang Anda ajukan ke asisten bukan percakapan pribadi dari sudut pandang perusahaan Anda. Sebaliknya, dokumen tidak terbuka bagi semua orang — karyawan hanya menerima jawaban dari dokumen departemennya sendiri dan dokumen yang ditandai sebagai dokumen bersama. Pertanyaan yang diajukan melalui Slack tidak tersimpan sebagai riwayat chat di aplikasi. Dari sisi kami, akses ke basis data produksi dibatasi pada operator layanan dan hanya digunakan untuk pemeliharaan, dukungan, dan penanganan insiden." },
  { title: "7. Berbagi Data dengan Pihak Ketiga", body: "Kami berbagi data secara terbatas dengan: Google LLC (Gemini API — pengindeksan dokumen dan penyusunan jawaban, lihat bagian 4); Groq Inc. (penyusunan jawaban dan ringkasan); Midtrans (pemrosesan pembayaran, berlisensi Bank Indonesia); Neon Inc. (penyimpanan basis data); Vercel Inc. (hosting aplikasi, serta Vercel Web Analytics yang mengukur kunjungan secara agregat tanpa cookie); Google (Google Analytics 4 — **hanya aktif setelah Anda menekan Terima pada banner cookie**); Resend (pengiriman email transaksional); Slack Technologies (hanya bila Anda memasang integrasi Slack — pertanyaan dan jawaban dikirim ke workspace Slack Anda sendiri); dan Google Drive (hanya saat admin Anda memakai fitur impor; token akses Drive hanya berada di peramban admin dan tidak kami simpan). Kami tidak membagikan data Anda kepada pihak lain tanpa persetujuan eksplisit Anda, kecuali bila diwajibkan oleh hukum yang berlaku." },
  { title: "8. Lokasi Penyimpanan dan Transfer ke Luar Wilayah Indonesia", body: "Basis data kami dijalankan pada Neon di infrastruktur AWS **wilayah Singapura (ap-southeast-1)**, dan aplikasi berjalan pada infrastruktur Vercel. Penyedia AI, pembayaran, email, dan analitik yang disebut pada bagian 7 juga memproses data di luar wilayah Indonesia. **Dengan menggunakan layanan ini Anda mengetahui dan menyetujui bahwa data diproses di luar wilayah Republik Indonesia.** Kami memilih penyedia yang memberikan komitmen perlindungan data setidaknya setara dengan yang diwajibkan UU PDP." },
  { title: "9. Keamanan", body: "Seluruh koneksi dienkripsi dengan TLS. Kata sandi disimpan dalam bentuk hash. Kunci API penyedia milik Anda dan token Slack disimpan terenkripsi dengan AES-256-GCM, terikat pada ruang kerja dan kolom penyimpanannya. Isolasi antar-ruang kerja ditegakkan dengan Row-Level Security di basis data ditambah pemeriksaan otorisasi di setiap jalur permintaan. Verifikasi dua langkah tersedia untuk semua akun. Tidak ada sistem yang sepenuhnya bebas risiko, dan kami tidak menyatakan sebaliknya." },
  { title: "10. Cookie dan Penyimpanan Lokal", body: "Kami memakai cookie sesi untuk autentikasi — ini wajib, karena tanpanya Anda tidak dapat tetap masuk. Di penyimpanan lokal peramban (localStorage) kami menyimpan pilihan bahasa, status persetujuan cookie, dan status opt-out analitik; ketiganya tidak dikirim ke server kami. Google Analytics 4 baru dimuat dan baru menulis cookie **setelah Anda menekan Terima pada banner persetujuan**; menekan Tolak berarti GA tidak pernah dimuat. Vercel Web Analytics berjalan tanpa cookie dan hanya mengukur kunjungan secara agregat; Anda dapat menonaktifkannya per perangkat melalui halaman /analytics-optout." },
  { title: "11. Retensi Data", body: "Dokumen beserta teks, potongan, dan vektornya disimpan selama masih ada di ruang kerja Anda, dan terhapus permanen saat admin menghapusnya. Riwayat chat disimpan selama akun aktif. Catatan sesi login terhapus saat sesi kedaluwarsa. Catatan transaksi pembayaran disimpan lebih lama sebagai catatan keuangan sesuai kewajiban pembukuan yang berlaku. Email yang masuk melalui formulir halaman depan disimpan sampai Anda meminta penghapusannya. Log operasional pada penyedia infrastruktur kami disimpan maksimal 90 hari. Setelah permintaan penghapusan akun, data Anda dihapus dalam 30 hari. Perlu diketahui bahwa **saat langganan berakhir, dokumen dan akun karyawan yang melebihi batas paket gratis dibekukan, bukan dihapus**, dan pulih kembali bila Anda berlangganan lagi." },
  { title: "12. Hak Anda (UU PDP No. 27/2022)", body: "Anda berhak: memperoleh informasi tentang pemrosesan data Anda; mengakses dan memperoleh salinan data Anda; mengoreksi data yang tidak akurat; menghapus akun beserta datanya; menarik persetujuan yang pernah Anda berikan; mengajukan keberatan atas pemrosesan tertentu; serta mengajukan pengaduan kepada lembaga yang berwenang. **Permintaan-permintaan ini kami tangani secara manual — belum ada tombol mandiri di aplikasi.** Kirimkan permintaan Anda ke hello@intellibaseai.com dari alamat email akun Anda; kami menanggapi selambat-lambatnya 30 hari, dan biasanya jauh lebih cepat. Untuk data karyawan pada akun Perusahaan, permintaan sebaiknya diajukan lebih dulu kepada admin ruang kerja Anda sebagai Pengendali Data." },
  { title: "13. Insiden Kebocoran Data", body: "Apabila terjadi kegagalan pelindungan data pribadi, kami akan memberitahukan secara tertulis kepada pemilik data pribadi yang terdampak dan kepada lembaga yang berwenang **selambat-lambatnya 3 x 24 jam** sejak diketahui, sebagaimana diwajibkan UU PDP, disertai penjelasan data yang terungkap, waktu dan cara terungkapnya, serta langkah penanganan dan pemulihan yang kami lakukan." },
  { title: "14. Perubahan Kebijakan", body: "Perubahan material pada kebijakan ini — termasuk perubahan daftar penyedia pihak ketiga atau cara data Anda diproses — akan diberitahukan melalui email atau notifikasi dalam aplikasi sebelum berlaku. Tanggal pembaruan terakhir selalu tercantum di bagian atas halaman ini." },
  { title: "15. Kontak", body: "Pertanyaan, permintaan hak, atau keberatan terkait data pribadi: hello@intellibaseai.com" },
];

const EN_SECTIONS: readonly LegalSection[] = [
  { title: "1. Who We Are and Our Role", body: "IntelliBase AI is an AI-powered internal knowledge base service operated from Indonesia. This policy explains how we treat personal data. Under Indonesian Law No. 27 of 2022 on Personal Data Protection: for the contents of documents you upload and the employee data you register, **your organisation is the Data Controller and we are the Processor**, processing on your instructions; for account data, billing data and operational technical data, we act as Controller. Contact for all personal data matters: hello@intellibaseai.com" },
  { title: "2. Data We Collect", body: "(a) Account data: name, email address, workspace or company name, account type, role (admin or employee), department, email verification status, 2FA status, and your password stored as a hash — never as plain text. (b) Documents: files you upload are extracted into text; what we store is the extracted text, its chunks, their vector representations, and an automatic summary. **The original file itself is not retained after extraction.** (c) Chat activity: questions, AI answers with their source citations, and thumbs up/down feedback. (d) Technical data: the IP address and user agent recorded on login sessions, plus IP addresses used transiently for rate limiting (abuse prevention). (e) Transaction data: order id, plan, amount and payment status. We never receive or store your card numbers. (f) If you install the Slack integration: the Slack member id and the Slack profile email address, used to match the asker to an account in your workspace. (g) If you submit the landing page form: your email address, language choice, and whether you signed up as a company or an individual." },
  { title: "3. Purposes and Legal Basis", body: "Your data is processed to: provide the search and AI chat service; index documents; enforce plan limits and quotas; maintain security and prevent abuse; process payments; send transactional email (verification, password reset, notifications); provide support; and understand site usage in aggregate. The bases for processing are performance of our contract with you, compliance with legal obligations (e.g. financial records), our legitimate interest limited to service security and continuity, and your consent for the things that genuinely ask for it, such as analytics and marketing follow-up. **We do not sell your data and we do not use your document contents to train models of our own.**" },
  { title: "4. Processing by AI Providers", highlight: true, body: "This service runs on top of third-party AI providers, so your document contents leave our systems in the following circumstances. **The full contents of documents you upload are sent to Google (Gemini API) to build a search index.** When a question is answered, that question and the relevant document excerpts are sent to Groq Inc.; if Groq is at its usage limit, those excerpts go to Google (Gemini API) instead. The opening of each document (roughly the first 2,000 characters) is also sent to Groq for an automatic summary. Groq states that it does not use customer API data to train its models. **Our Gemini account is currently on the free tier, and Google's terms for that tier allow Google to use submitted content to improve their services, including model training.** We state this plainly because it is the one thing on this page you are better off deciding about before uploading rather than after. **There is a way out on every paid plan — Personal for Individual accounts, and Professional, Enterprise and Custom for Company accounts: install your own Groq and Gemini API keys from the Subscription tab in the admin dashboard, and from that point indexing and answers are processed through your provider accounts, under the terms you agreed with those providers yourself. The Free Starter plan cannot install its own keys, so documents on a free account are always processed through our shared provider accounts, including the free-tier Gemini account described above.** Your keys are stored encrypted and can be removed at any time. Keys apply per provider: installing only a Gemini key does not move answer generation off our Groq account, and if you install keys without a Gemini key we disable our Gemini fallback rung rather than routing your documents into our free-tier account." },
  { title: "5. Specific Personal Data", highlight: true, body: "**This service is not intended for patient medical records, individual health data, personal financial data, biometric data, or other specific personal data as defined by the Indonesian PDP Law.** Please remove individual identifiers from documents before uploading — this knowledge base is designed for internal reference documents such as SOPs, clinical pathways, clinical practice guidelines, policies and accreditation manuals. As set out in section 4, document contents are sent to third-party AI providers, so uploading specific personal data on a free account means that data is processed on our shared provider accounts. If you must process such data, contact us first for a written data processing agreement." },
  { title: "6. Who Can See Your Data Inside the Application", highlight: true, body: "On Company accounts, **a workspace admin can see the question and answer history of every employee in their workspace, including the asker's name and email**, via the Audit Log tab in the admin dashboard. Employees should know this: the questions you ask the assistant are not private conversations from your company's point of view. Documents, conversely, are not open to everyone — an employee only receives answers from their own department's documents and documents marked as shared. Questions asked through Slack are not stored as chat history in the application. On our side, access to the production database is limited to the service operator and used only for maintenance, support and incident handling." },
  { title: "7. Sharing Data with Third Parties", body: "We share data on a limited basis with: Google LLC (Gemini API — document indexing and answer composition, see section 4); Groq Inc. (answer and summary generation); Midtrans (payment processing, licensed by Bank Indonesia); Neon Inc. (database storage); Vercel Inc. (application hosting, and Vercel Web Analytics which measures visits in aggregate without cookies); Google (Google Analytics 4 — **only active after you press Accept on the cookie banner**); Resend (transactional email delivery); Slack Technologies (only if you install the Slack integration — questions and answers are delivered into your own Slack workspace); and Google Drive (only when your admin uses the import feature; the Drive access token stays in the admin's browser and is not stored by us). We do not share your data with any other party without your explicit consent, except where required by applicable law." },
  { title: "8. Storage Location and Transfer Outside Indonesia", body: "Our database runs on Neon on AWS infrastructure in the **Singapore region (ap-southeast-1)**, and the application runs on Vercel infrastructure. The AI, payment, email and analytics providers named in section 7 also process data outside Indonesia. **By using this service you acknowledge and agree that data is processed outside the territory of the Republic of Indonesia.** We select providers whose data protection commitments are at least equivalent to what the PDP Law requires." },
  { title: "9. Security", body: "All connections are encrypted with TLS. Passwords are stored hashed. Your provider API keys and Slack tokens are stored encrypted with AES-256-GCM, bound to the workspace and the column they are stored in. Isolation between workspaces is enforced by Row-Level Security in the database plus authorisation checks on every request path. Two-factor authentication is available on all accounts. No system is entirely free of risk, and we do not claim otherwise." },
  { title: "10. Cookies and Local Storage", body: "We use a session cookie for authentication — this one is required, since without it you cannot stay signed in. In your browser's local storage we keep your language choice, your cookie consent state, and your analytics opt-out state; none of the three is sent to our servers. Google Analytics 4 is loaded and writes cookies **only after you press Accept on the consent banner**; pressing Decline means GA is never loaded at all. Vercel Web Analytics runs without cookies and only measures visits in aggregate; you can switch it off per device at /analytics-optout." },
  { title: "11. Data Retention", body: "Documents and their text, chunks and vectors are kept for as long as they exist in your workspace, and are permanently deleted when an admin deletes them. Chat history is kept while the account is active. Login session records are removed when the session expires. Payment transaction records are kept longer as financial records, in line with applicable bookkeeping obligations. Emails submitted through the landing page form are kept until you ask us to remove them. Operational logs at our infrastructure providers are retained for a maximum of 90 days. After an account deletion request, your data is deleted within 30 days. Note that **when a subscription lapses, documents and employee accounts above the free plan's limits are frozen, not deleted**, and are restored if you subscribe again." },
  { title: "12. Your Rights (Indonesian PDP Law No. 27/2022)", body: "You have the right to: be informed about the processing of your data; access and obtain a copy of your data; correct inaccurate data; delete your account and its data; withdraw consent you previously gave; object to certain processing; and lodge a complaint with the competent authority. **These requests are handled manually — there is no self-service button in the application yet.** Send your request to hello@intellibaseai.com from your account email address; we respond within 30 days at the latest, and usually far sooner. For employee data on a Company account, requests should first be directed to your workspace admin as the Data Controller." },
  { title: "13. Data Breach Incidents", body: "In the event of a personal data protection failure, we will notify the affected data subjects and the competent authority in writing **within 3 x 24 hours** of becoming aware of it, as required by the PDP Law, including what data was exposed, when and how it was exposed, and the containment and recovery steps we have taken." },
  { title: "14. Policy Changes", body: "Material changes to this policy — including changes to the list of third-party providers or to how your data is processed — will be communicated via email or in-app notification before they take effect. The last updated date is always shown at the top of this page." },
  { title: "15. Contact", body: "Questions, rights requests, or objections regarding personal data: hello@intellibaseai.com" },
];

const CONTENT = {
  id: {
    title: "Kebijakan Privasi",
    updated: "Terakhir diperbarui: 19 Agustus 2026",
    login: "Masuk",
    intro: "Bagian yang disorot adalah yang paling menentukan: ke mana isi dokumen Anda dikirim dan cara memindahkannya ke akun penyedia Anda sendiri, dokumen apa yang sebaiknya tidak diunggah, dan siapa saja yang dapat melihat pertanyaan Anda di dalam aplikasi.",
    sections: ID_SECTIONS,
  },
  en: {
    title: "Privacy Policy",
    updated: "Last updated: August 19, 2026",
    login: "Sign In",
    intro: "The highlighted sections are the ones that decide the most: where your document contents are sent and how to move that onto your own provider accounts, which documents are better not uploaded, and who can see your questions inside the application.",
    sections: EN_SECTIONS,
  },
};

export default function PrivacyPage() {
  const { lang } = useLang();
  const T = CONTENT[lang];

  return (
    <div className="min-h-screen bg-background">
      <nav className="border-b px-6 py-3 flex items-center justify-between">
        <Link href="/"><LogoFull size="sm" /></Link>
        <div className="flex items-center gap-3">
          <LanguageSwitcher />
          <Link href="/login" className="text-sm text-blue-600 hover:underline">{T.login}</Link>
        </div>
      </nav>
      <main className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-2xl md:text-3xl font-semibold tracking-[-0.015em] text-gray-900 mb-2">{T.title}</h1>
        <p className="text-gray-400 text-sm mb-6">{T.updated}</p>
        <p className="text-sm leading-relaxed text-gray-600 mb-10">{T.intro}</p>
        <LegalBody sections={T.sections} />
      </main>
      <SiteFooter lang={lang} />
    </div>
  );
}
